application:
  appName: app

spring:
  application:
    name: app

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/database
    username: database
    password: database
    hikari:
      auto-commit: false
  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
  server:
    port: 8080

services:
  negative-cpf:
    url: http://localhost:8081